version: '3.8'

services:
  web:
    build: .
    image: pefcortes/fullcycle
    container_name: fullcycle
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: air ./main.go -b 0.0.0.0